// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAPI.Persistance;

namespace StudentAPI.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20200503031136_CreateTimeTablesTable")]
    partial class CreateTimeTablesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentAPI.Core.Models.Seance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Heure");

                    b.Property<string>("Jour");

                    b.Property<string>("Lieu");

                    b.Property<int?>("TimeTableId");

                    b.Property<int>("TimeTanleId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("TimeTableId");

                    b.ToTable("Seances");
                });

            modelBuilder.Entity("StudentAPI.Core.Models.TimeTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassNbr");

                    b.Property<string>("Cycle");

                    b.Property<string>("SchoolYear");

                    b.Property<byte>("Semester");

                    b.Property<string>("Specility");

                    b.HasKey("Id");

                    b.ToTable("TimeTables");
                });

            modelBuilder.Entity("StudentAPI.Core.Models.Seance", b =>
                {
                    b.HasOne("StudentAPI.Core.Models.TimeTable", "TimeTable")
                        .WithMany("Seances")
                        .HasForeignKey("TimeTableId");
                });
#pragma warning restore 612, 618
        }
    }
}
