// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAPI.Persistance;

namespace StudentAPI.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20200504060539_UpdateTimeTablesTablev2")]
    partial class UpdateTimeTablesTablev2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentAPI.Core.Models.Seance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Heure")
                        .IsRequired();

                    b.Property<string>("Jour")
                        .IsRequired();

                    b.Property<string>("Lieu");

                    b.Property<string>("Module")
                        .IsRequired();

                    b.Property<int>("TimeTableId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("TimeTableId");

                    b.ToTable("Seances");
                });

            modelBuilder.Entity("StudentAPI.Core.Models.TimeTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassNbr");

                    b.Property<string>("Cycle")
                        .IsRequired();

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("SchoolYear");

                    b.Property<string>("Semester")
                        .IsRequired();

                    b.Property<string>("Specility")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TimeTables");
                });

            modelBuilder.Entity("StudentAPI.Core.Models.Seance", b =>
                {
                    b.HasOne("StudentAPI.Core.Models.TimeTable", "TimeTable")
                        .WithMany("Seances")
                        .HasForeignKey("TimeTableId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
