//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDomain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Planning> Plannings { get; set; }
        public virtual DbSet<Journee> Journees { get; set; }
        public virtual DbSet<Seance> Seances { get; set; }
        public virtual DbSet<InfoSeance> InfoSeances { get; set; }
        public virtual DbSet<Bloc> Blocs { get; set; }
        public virtual DbSet<Salle> Salles { get; set; }
        public virtual DbSet<Etablissement> Etablissements { get; set; }
        public virtual DbSet<Departement> Departements { get; set; }
        public virtual DbSet<Formation> Formations { get; set; }
        public virtual DbSet<DomaineFormation> DomaineFormations { get; set; }
        public virtual DbSet<Filiere> Filieres { get; set; }
        public virtual DbSet<Specialite> Specialites { get; set; }
        public virtual DbSet<NiveauSpecialite> NiveauSpecialites { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Groupe> Groupes { get; set; }
        public virtual DbSet<SousGroupe> SousGroupes { get; set; }
        public virtual DbSet<Matiere> Matieres { get; set; }
        public virtual DbSet<UnitePedagogique> UnitePedagogiques { get; set; }
        public virtual DbSet<MatiereRef> MatiereRefs { get; set; }
        public virtual DbSet<Personne> Personnes { get; set; }
        public virtual DbSet<Parcour> Parcours { get; set; }
        public virtual DbSet<Resultat> Resultats { get; set; }
        public virtual DbSet<ResultatUnite> ResultatUnites { get; set; }
        public virtual DbSet<ResultatMatiere> ResultatMatieres { get; set; }
        public virtual DbSet<RelationCommunication> RelationCommunications { get; set; }
        public virtual DbSet<Discussion> Discussions { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<DocumentPartage> DocumentPartages { get; set; }
    }
}
