//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace StudentAPI.Core.Models
{
    public partial class Message
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public System.DateTime DateMsg { get; set; }
        public int DiscussionId { get; set; }
        public DateTime LastUpdate { get; set; }


        public virtual Discussion Discussion { get; set; }
    }
}
