//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAPI.Core.Models
{
    public partial class PlanningSGroupe : Planning
    {
        public int PlanningGroupeId { get; set; }
        public int SousGroupeId { get; set; }

        public virtual PlanningGroupe PlanningGroupe { get; set; }
        public virtual SousGroupe SousGroupe { get; set; }
    }
}
