//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAPI.Core.Models
{
    using System;
    using System.Collections.Generic;

    public partial class ResultatUnite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResultatUnite()
        {
            this.ResultatMatieres = new HashSet<ResultatMatiere>();
        }

        public int Id { get; set; }
        public Nullable<double> MoyenneUnite { get; set; }
        public Nullable<double> CreditUnite { get; set; }
        public int UnitePedagogiqueId { get; set; }
        public int ResultatId { get; set; }
        public DateTime LastUpdate { get; set; }


        public virtual UnitePedagogique UnitePedagogique { get; set; }
        public virtual Resultat Resultat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultatMatiere> ResultatMatieres { get; set; }
    }
}
