//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAPI.Core.Models
{
    using System.Collections.Generic;

    public partial class SousGroupe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SousGroupe()
        {
            this.PlanningSGroupes = new HashSet<PlanningSGroupe>();
            this.Parcours = new HashSet<Parcour>();
        }

        public int Id { get; set; }
        public string RefSousGroupe { get; set; }
        public int GroupeId { get; set; }

        public virtual Groupe Groupe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanningSGroupe> PlanningSGroupes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parcour> Parcours { get; set; }
    }
}
